# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160727_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='avah',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='ogoh',
            field=models.BooleanField(),
        ),
    ]
